//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD.Infra.pesqwebservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:pesqwebservice", ConfigurationName="pesqwebservice.pesqwebservicePortType")]
    public interface pesqwebservicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pesqwebservice#getalldatabycpf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getalldatabycpf(string usr, string pwd, string emp, string cpf);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pesqwebservice#getalldatabycpf", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getalldatabycpfAsync(string usr, string pwd, string emp, string cpf);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pesqwebservice#getveicdata", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getveicdata(string usr, string pwd, string emp, string veic);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:pesqwebservice#getveicdata", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getveicdataAsync(string usr, string pwd, string emp, string veic);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface pesqwebservicePortTypeChannel : BD.Infra.pesqwebservice.pesqwebservicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class pesqwebservicePortTypeClient : System.ServiceModel.ClientBase<BD.Infra.pesqwebservice.pesqwebservicePortType>, BD.Infra.pesqwebservice.pesqwebservicePortType {
        
        public pesqwebservicePortTypeClient() {
        }
        
        public pesqwebservicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public pesqwebservicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public pesqwebservicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public pesqwebservicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getalldatabycpf(string usr, string pwd, string emp, string cpf) {
            return base.Channel.getalldatabycpf(usr, pwd, emp, cpf);
        }
        
        public System.Threading.Tasks.Task<string> getalldatabycpfAsync(string usr, string pwd, string emp, string cpf) {
            return base.Channel.getalldatabycpfAsync(usr, pwd, emp, cpf);
        }
        
        public string getveicdata(string usr, string pwd, string emp, string veic) {
            return base.Channel.getveicdata(usr, pwd, emp, veic);
        }
        
        public System.Threading.Tasks.Task<string> getveicdataAsync(string usr, string pwd, string emp, string veic) {
            return base.Channel.getveicdataAsync(usr, pwd, emp, veic);
        }
    }
}
